version: '3.8'

services:
  # Serviço 1: O nosso banco de dados SQL Server
  biblioteca-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-server-container
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SuaSenhaForteAqui123!
    ports:
      - "1433:1433"
    networks:
      - biblioteca-network

  # Serviço 2: A nossa API .NET 10 que criamos a imagem
  biblioteca-api:
    image: biblioteca-api
    container_name: biblioteca-api-container
    build:
      context: ./BibliotecaAPI
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # Aqui mudamos o Connection String para apontar para o nome do serviço do banco!
      - ConnectionStrings__DefaultConnection=Server=biblioteca-db;Database=BibliotecaDb;User Id=sa;Password=SuaSenhaForteAqui123!;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - biblioteca-db
    networks:
      - biblioteca-network

networks:
  biblioteca-network:
    driver: bridge