name: Conexão CI - .NET & Docker

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar o .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    # Força o restore direto no arquivo de projeto
    - name: Restaurar pacotes
      run: dotnet restore ./BibliotecaAPI/BibliotecaAPI.csproj

    # Força o build direto no arquivo de projeto
    - name: Compilar a aplicação (Build)
      run: dotnet build ./BibliotecaAPI/BibliotecaAPI.csproj --no-restore --configuration Release

    # Builda o Docker usando o contexto correto da raiz
    - name: Testar build da Imagem Docker
      run: docker build -t biblioteca-api:test -f ./BibliotecaAPI/Dockerfile .
